nginx:
    image: localhost:5000/cheton/nginx
    links:
        - node1
        - node2
        - node3
    ports:
        - "80:80"
node1:
    image: localhost:5000/cheton/node:0.8.0
    links:
        - redis
    ports:
        - "8080"
node2:
    image: localhost:5000/cheton/node:0.8.0
    links:
        - redis
    ports:
        - "8080"
node3:
    image: localhost:5000/cheton/node:0.8.0
    links:
        - redis
    ports:
        - "8080"
redis:
    image: localhost:5000/cheton/redis
    ports:
        - "6379"
